
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/productmanagementproject?createDatabaseIfNotExist=true
  config:
    activate:
      on-profile:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false



server:
  port: 8085
  error:
    include-stacktrace: always
    include-message: always
    include-exception: true

logging:
  level:
    root: INFO
    com.student.productmanagementproject: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql: INFO
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
  port: 9000
spring:
  config:
    activate:
      on-profile: test